### ISSUE TITLE
[HELP]There is no completion items display for third-party deps in neovim/helix but it does in vscode

### ISSUE THREAD

**Issue by lost22git** [zigtools/zls#1092]
### Zig Version

0.11.0-dev.2247+38ee46dda

### Zig Language Server Version

0.10.0-dev.364+7ef2244

### nvim lsp-config
```lua
nvim_lsp.zls.setup {
    on_attach = on_attach,
    capabilities = capabilities,
    cmd = { 'zls' }
  }
```

### helix languages.toml 
```toml
[[language]]
name = "zig"
scope = "source.zig"
injection-regex = "zig"
file-types = ["zig"]
roots = ["build.zig"]
auto-format = true
comment-token = "//"
language-server = { command = "zls" }
indent = { tab-width = 4, unit = "    " }
formatter = { command = "zig", args = ["fmt", "--stdin"] }
```

### Expected Behavior

Show 3rd-party deps completion items 

### Actual Behavior

Not
